/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFileChooser;

/**
 *
 * @author rr
 */
public class SeletorArquivo extends JFileChooser{
     public String path;
     public boolean captured;
     
    public SeletorArquivo() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                    

    @Override
    public void approveSelection() {
        path = this.getCurrentDirectory().toString();
        System.out.println(path);
        captured = true;
        this.setVisible(false);
    }
}
